# docker-compose.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: my-backend
    restart: unless-stopped
    
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000   